version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t cliwrap/bionic .
      - run: docker run --rm -e "HOSTUID=`id -u`" cliwrap/bionic pwd | grep '^/home/hostuser$'
